Repository SAP/ui5-webcomponents-react, pull requests merged in 2021-08, with the labels that each got.

#1602 refactor(AnalyticalTable): rename `title` to `header`
  packages/main/src/components/AnalyticalTable/AnalyticalTable.stories.mdx
  packages/main/src/components/AnalyticalTable/AnalyticalTable.test.tsx
  packages/main/src/components/AnalyticalTable/index.tsx
Labels: breaking change

#1604 refactor(MessageBox): rename `title` to `titleText`
  packages/base/codemods/renamePropsV18.js
  packages/main/src/components/MessageBox/MessageBox.test.tsx
  packages/main/src/components/MessageBox/index.tsx
Labels: breaking change

#1605 refactor(VariantManagement): rename `popupTitle` to `titleText`
  packages/base/codemods/renamePropsV18.js
  packages/main/src/components/VariantManagement/VariantManagement.stories.mdx
  packages/main/src/components/VariantManagement/index.tsx
  packages/main/src/i18n/messagebundle.properties
Labels: breaking change

#1601 refactor(AnalyticalCardHeader): rename props and don't render unnecessary elements
  packages/base/codemods/renamePropsV18.js
  packages/main/src/components/AnalyticalCard/AnalyticalCard.stories.mdx
  packages/main/src/components/AnalyticalCard/AnalyticalCard.test.tsx
  packages/main/src/components/AnalyticalCard/__snapshots__/AnalyticalCard.test.tsx.snap
  packages/main/src/components/AnalyticalCardHeader/AnalyticalCardHeader.test.tsx
  packages/main/src/components/AnalyticalCardHeader/__snapshots__/AnalyticalCardHeader.test.tsx.snap
  packages/main/src/components/AnalyticalCardHeader/index.tsx
Labels: breaking change

#1910 refactor(ObjectPage): rename `heading` to `titleText`
  packages/base/codemods/renamePropsV18.js
  packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
  packages/main/src/components/ObjectPage/ObjectPage.test.tsx
  packages/main/src/components/ObjectPage/ObjectPageAnchorButton.tsx
  packages/main/src/components/ObjectPage/index.tsx
  packages/main/src/components/ObjectPageSection/ObjectPageSection.test.tsx
  packages/main/src/components/ObjectPageSection/index.tsx
  packages/main/src/components/ObjectPageSubSection/ObjectPageSubSection.test.tsx
  packages/main/src/components/ObjectPageSubSection/index.tsx
Labels: breaking change

#1912 refactor(DynamicPageTitle): rename props
  packages/base/codemods/renamePropsV18.js
  packages/main/src/components/AnalyticalCard/AnalyticalCard.stories.mdx
  packages/main/src/components/DynamicPage/DynamicPage.stories.mdx
  packages/main/src/components/DynamicPage/DynamicPage.test.tsx
  packages/main/src/components/DynamicPage/__snapshots__/DynamicPage.test.tsx.snap
  packages/main/src/components/DynamicPageTitle/index.tsx
  packages/main/src/components/ObjectPage/ObjectPage.stories.mdx
  packages/main/src/components/ObjectPage/__snapshots__/ObjectPage.test.tsx.snap
  packages/main/src/components/ObjectPage/index.tsx
  packages/main/src/components/ObjectPageSection/__snapshots__/ObjectPageSection.test.tsx.snap
  packages/main/src/components/ObjectPageSection/index.tsx
  packages/main/src/components/ObjectPageSubSection/__snapshots__/ObjectPageSubSection.test.tsx.snap
  packages/main/src/components/ObjectPageSubSection/index.tsx
Labels: breaking change

#1638 chore: add missing component PropTypes exports
  packages/main/src/components/ActionSheet/index.tsx
  packages/main/src/components/AnalyticalCard/index.tsx
  packages/main/src/components/AnalyticalCardHeader/index.tsx
  packages/main/src/components/AnalyticalTable/index.tsx
  packages/main/src/components/DynamicPage/index.tsx
  packages/main/src/components/DynamicPageHeader/index.tsx
  packages/main/src/components/DynamicPageTitle/index.tsx
  packages/main/src/components/FilterBar/index.tsx
  packages/main/src/components/FilterGroupItem/index.tsx
  packages/main/src/components/FlexBox/index.tsx
  packages/main/src/components/Form/index.tsx
  packages/main/src/components/FormGroup/index.tsx
  packages/main/src/components/FormItem/index.tsx
  packages/main/src/components/Grid/index.tsx
  packages/main/src/components/Loader/index.tsx
  packages/main/src/components/MessageBox/index.tsx
  packages/main/src/components/ObjectPage/index.tsx
  packages/main/src/components/ObjectPageSection/index.tsx
  packages/main/src/components/ObjectPageSubSection/index.tsx
  packages/main/src/components/ObjectStatus/index.tsx
  packages/main/src/components/Text/index.tsx
  packages/main/src/components/ThemeProvider/index.tsx
  packages/main/src/components/Toolbar/index.tsx
  packages/main/src/components/ToolbarSeparator/index.tsx
  packages/main/src/components/ToolbarSpacer/index.tsx
  packages/main/src/components/VariantManagement/index.tsx
  packages/main/src/dist/ActionSheet.ts
  packages/main/src/dist/AnalyticalCard.ts
  packages/main/src/dist/AnalyticalCardHeader.ts
  packages/main/src/dist/AnalyticalTable.ts
  packages/main/src/dist/DynamicPage.ts
  packages/main/src/dist/DynamicPageHeader.ts
  packages/main/src/dist/DynamicPageTitle.ts
  packages/main/src/dist/FilterBar.ts
  packages/main/src/dist/FilterGroupItem.ts
  packages/main/src/dist/FlexBox.ts
  packages/main/src/dist/Form.ts
  packages/main/src/dist/FormGroup.ts
  packages/main/src/dist/FormItem.ts
  packages/main/src/dist/Grid.ts
  packages/main/src/dist/Loader.ts
  packages/main/src/dist/MessageBox.ts
  packages/main/src/dist/ObjectPage.ts
  packages/main/src/dist/ObjectPageSection.ts
  packages/main/src/dist/ObjectPageSubSection.ts
  packages/main/src/dist/ObjectStatus.ts
  packages/main/src/dist/Text.ts
  packages/main/src/dist/ThemeProvider.ts
  packages/main/src/dist/Toolbar.ts
  packages/main/src/dist/ToolbarSeparator.ts
  packages/main/src/dist/ToolbarSpacer.ts
  packages/main/src/dist/VariantManagement.ts
Labels: breaking change

#1911 feat(Column/Bar/ColumnWithTrend-Chart): add custom coloring of elements
  packages/charts/src/components/BarChart/BarChart.stories.mdx
  packages/charts/src/components/BarChart/BarChart.tsx
  packages/charts/src/components/ColumnChart/ColumnChart.stories.mdx
  packages/charts/src/components/ColumnChart/ColumnChart.tsx
  packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.stories.mdx
  packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.tsx
  packages/charts/src/dist/Utils.ts
  packages/charts/src/internal/Utils.ts
Labels: feature-request

#1960 feat(BulletChart): create new type of chart
  packages/charts/src/components/BulletChart/BulletChart.stories.mdx
  packages/charts/src/components/BulletChart/BulletChart.test.tsx
  packages/charts/src/components/BulletChart/BulletChart.tsx
  packages/charts/src/components/BulletChart/ComparisonLine.tsx
  packages/charts/src/components/BulletChart/Placeholder.tsx
  packages/charts/src/components/BulletChart/__snapshots__/BulletChart.test.tsx.snap
  packages/charts/src/components/ComposedChart/ComposedChart.stories.mdx
  packages/charts/src/dist/BulletChart.ts
  packages/charts/src/dist/BulletChartPlaceholder.ts
  packages/charts/src/dist/Utils.ts
  packages/charts/src/index.ts
  packages/charts/src/internal/ChartContainer.tsx
  packages/charts/src/internal/Utils.ts
  packages/charts/src/internal/XAxisTicks.tsx
  packages/charts/src/internal/YAxisTicks.tsx
  packages/charts/src/resources/DemoProps.ts
  shared/tests/chartUtils.tsx
Labels: feature-request

#1999 fix(ColumnChartWithTrend): fix sync of charts
  packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.stories.mdx
  packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.test.tsx
  packages/charts/src/components/ColumnChartWithTrend/ColumnChartWithTrend.tsx
  packages/charts/src/components/ColumnChartWithTrend/__snapshots__/ColumnChartWithTrend.test.tsx.snap
  packages/charts/src/components/ComposedChart/index.tsx
  packages/charts/src/hooks/usePrepareTrendMeasures.ts
  packages/charts/src/interfaces/ICartesianChartConfig.ts
Labels: bug
